name: Validate DGS csv

on:
  pull_request:
    branches:
      - master
  push: 
    branches:
      - github_actions

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas numpy pytest pytest-mock 
      - name: Validate data with pytest
        run: pytest tests/test_dgs_data.py -s -vv --junitxml=tests/junit/test-results.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@master
        with:
          name: pytest-results
          path: tests/junit/test-results.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: always()